spring.application.name=JDEmcpPur
mcp.ai.mcp.server.name=JDEMCPPur
mcp.ai.mcp.server.version=1.0.0

# MCP Server Configuration
spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.streamable-http.mcp-endpoint=/mcp
spring.ai.mcp.server.stdio=false
spring.ai.mcp.server.type=sync
DANGEROUSLY_OMIT_AUTH=true

